<a href="https://colab.research.google.com/github/LuisR-crypto/THC_LRNP_TAREAS/blob/main/29-10-2024_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<font color="Red" face="Comic Sans MS,arial">
  <h1 align="center"><i>Numpy </i></h1>
  </font>
  
> Elaborado por: Jesús Iván Coss Calderón. mat_ing_coss@ciencias.unam.mx

**Objetivo general**

* Aprender los fundamentos de la biblioteca de Numpy

**Objetivos particulares**

* Entender el uso de los métodos de Numpy

[**Regresa al notebook principal**](https://github.com/seismomat/HerramientasComputacionales/blob/main/TemarioDePython/Temario%20de%20Python.ipynb)

<a name='c1'></a>

## Contenido

- [¿Qué es NumPy?](#1)
    - [¿Por qué usar NumPy?](#1-1)
    - [¿Por qué NumPy es más rápido que las listas?](#1-2)
    - [Instalación de Numpy](#1-3)
    - [Importando Numpy](#1-4)
- [Crear un Objeto ndarray de NumPy](#2)
    - [Arreglos 0-D](#2-1)
    - [Arreglos 1-D](#2-2)
    - [Arreglos 2-D](#2-3)
    - [Arreglos 3-D](#2-4)
    - [Checando las dimensiones de los arreglos](#2-5)
    - [Arreglos de dimensión mayor](#2-6)
- [Acceso a elementos](#3)
    - [Arreglos 1-D](#3-1)
    - [Arreglos 2-D](#3-2)
    - [Arreglos 3-D](#3-3)
- [Slicing](#4)
    - [Arreglos 1-D](#4-1)
        - [Paso](#4-1-1)
    - [Arreglos 2-D](#4-2)
- [Buscando en arreglos](#5)
- [Filtrado](#6)

<a name='1'></a>

# ¿Qué es NumPy?
[regresar al contenido](#c1)

NumPy es una biblioteca de Python utilizada para trabajar con matrices.

También tiene funciones para trabajar en el ámbito del álgebra lineal, la transformada de Fourier y las matrices.

NumPy fue creado en 2005 por Travis Oliphant. Es un proyecto de código abierto y puedes utilizarlo libremente.

NumPy significa "Numerical Python" (Python Numérico).

<a name='1-1'></a>

## ¿Por qué usar NumPy?
[regresar al contenido](#c1)

En Python, tenemos listas que cumplen la función de arrays, pero son lentas de procesar.

NumPy tiene como objetivo proporcionar un objeto de array que sea hasta 50 veces más rápido que las listas tradicionales de Python.

El objeto de array en NumPy se llama ndarray y proporciona muchas funciones de soporte que facilitan trabajar con ndarray.

Los arrays se utilizan con mucha frecuencia en la ciencia de datos, donde la velocidad y los recursos son muy importantes.

<a name='1-2'></a>

## ¿Por qué NumPy es más rápido que las listas?
[regresar al contenido](#c1)

Los arrays de NumPy se almacenan en un lugar continuo en la memoria, a diferencia de las listas, por lo que los procesos pueden acceder y manipularlos de manera muy eficiente.

Este comportamiento se llama "localidad de referencia" en informática.

Esta es la razón principal por la que NumPy es más rápido que las listas. Además, está optimizado para funcionar con las últimas arquitecturas de CPU.

<a name='1-3'></a>

## Instalación de Numpy
[regresar al contenido](#c1)

> pip install numpy

<a name='1-4'></a>

## Importando Numpy
[regresar al contenido](#c1)

> import numpy

o también se puede importar con algún alias

> import numpy as np

<a name='2'></a>

# Crear un Objeto ndarray de NumPy
[regresar al contenido](#c1)

`NumPy` se utiliza para trabajar con arrays. El objeto de array en NumPy se llama ndarray.

Podemos crear un objeto ndarray de NumPy utilizando la función `array()`.

In [1]:
import numpy as np

In [2]:
arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [3]:
arr1 = np.array((1, 2, 3, 4, 5))

print(arr1)

print(type(arr1))

[1 2 3 4 5]
<class 'numpy.ndarray'>


<a name='2-1'></a>

## Arreglos 0-D
[regresar al contenido](#c1)

Los arrays 0-D, o escalares, son los elementos en un array. Cada valor en un array se considera un array 0-D en sí mismo. En otras palabras, un array puede contener múltiples escalares como sus elementos.

In [4]:
arr = np.array(42)

print(arr)

42


<a name='2-2'></a>

## Arreglos 1-D
[regresar al contenido](#c1)

Un array que tiene arrays 0-D (escalares) como sus elementos se llama array unidimensional o 1-D. En otras palabras, es un array que contiene valores individuales en lugar de secuencias de valores.

In [5]:
arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


<a name='2-3'></a>

## Arreglos 2-D
[regresar al contenido](#c1)

Un array que tiene arrays 1-D como sus elementos se llama array 2-D.

A menudo se utilizan para representar matrices o tensores de segundo orden.

In [6]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)

[[1 2 3]
 [4 5 6]]


<a name='2-4'></a>

## Arreglos 3-D
[regresar al contenido](#c1)

Un array que tiene matrices 2-D como sus elementos se llama array 3-D.

A menudo se utilizan para representar un tensor de tercer orden.

In [7]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


<a name='2-5'></a>

## Checando las dimensiones de los arreglos
[regresar al contenido](#c1)

In [8]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim,a.shape)
print(b.ndim,b.shape)
print(c.ndim,c.shape)
print(d.ndim,d.shape)

0 ()
1 (5,)
2 (2, 3)
3 (2, 2, 3)


<a name='2-6'></a>

## Arreglos de dimensión mayor
[regresar al contenido](#c1)

In [9]:
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


<a name='3'></a>

# Acceso a elementos
[regresar al contenido](#c1)

La indexación de arrays es similar a acceder a un elemento de un array.

Puedes acceder a un elemento de un array haciendo referencia a su número de índice.

Los índices en los arrays de NumPy comienzan en 0, lo que significa que el primer elemento tiene un índice 0, el segundo tiene un índice 1, y así sucesivamente.

<a name='3-1'></a>

## Arreglos 1-D
[regresar al contenido](#c1)

In [10]:
arr = np.array([1, 2, 3, 4])

print(arr[0])

1


<a name='3-2'></a>

## Arreglos 2-D
[regresar al contenido](#c1)

Para acceder a elementos de arrays 2-D, podemos usar enteros separados por comas que representan la dimensión y el índice del elemento.

Piensa en los arrays 2-D como una tabla con filas y columnas, donde la dimensión representa la fila y el índice representa la columna.

In [11]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2do elemento de la 1er Fila: ', arr[0, 1])

2do elemento de la 1er Fila:  2


In [12]:
print('Quinto elemento de la 2da Fila', arr[1, 4])

Quinto elemento de la 2da Fila 10


<a name='3-3'></a>

## Arreglos 3-D
[regresar al contenido](#c1)

Para acceder a elementos de arrays 3-D, podemos usar enteros separados por comas que representan las dimensiones y el índice del elemento. Esto implica especificar la coordenada en cada dimensión para llegar al elemento deseado en el array tridimensional.

In [13]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2])

6


<a name='4'></a>

# Slicing
[regresar al contenido](#c1)

El slicing en Python significa tomar elementos desde un índice dado hasta otro índice dado.

Pasamos el slice en lugar del índice de esta manera: `[inicio:fin]`.

También podemos definir el paso, de esta manera: `[inicio:fin:paso]`.

- Si no especificamos el inicio, se considera 0.
- Si no especificamos el fin, se considera la longitud del array en esa dimensión.
- Si no especificamos el paso, se considera 1.

<a name='4-1'></a>

## Arreglos 1-D
[regresar al contenido](#c1)

In [14]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])

[2 3 4 5]


In [15]:
print(arr[4:])

[5 6 7]


In [16]:
print(arr[:4])

[1 2 3 4]


In [17]:
print(arr[-3:-1])

[5 6]


<a name='4-1-1'></a>

### Paso
[regresar al contenido](#c1)

> `arreglo[inicio:fin:paso]`

In [18]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2])

[2 4]


In [19]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[::2])

[1 3 5 7]


<a name='4-2'></a>

## Arreglos 2-D
[regresar al contenido](#c1)

In [20]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])

[7 8 9]


In [21]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 2])

[3 8]


In [22]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


<a name='5'></a>

# Buscando en arreglos
[regresar al contenido](#c1)

Puedes buscar un valor específico en un array y obtener los índices que coinciden con ese valor.

Para buscar en un array, utiliza el método `where()`. El método `where()` de NumPy te permite buscar elementos que cumplan con ciertas condiciones y devuelve los índices donde se encuentran esos elementos.

In [23]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)

(array([3, 5, 6]),)


In [24]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 0)

print(x)

(array([1, 3, 5, 7]),)


Existe un método llamado `searchsorted()` que realiza una búsqueda binaria en el array y devuelve el índice donde se insertaría el valor especificado para mantener el orden de búsqueda.

Se asume que el método `searchsorted()` se utiliza en arrays ordenados, ya que se basa en la búsqueda binaria, que funciona eficientemente en datos ordenados.

In [25]:
arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7)

print(x)

1


De forma predeterminada, se devuelve el índice más a la izquierda al buscar un valor en un array, pero podemos especificar `side='right'` para obtener en su lugar el índice más a la derecha.

In [26]:
arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7, side='right')

print(x)

2


In [27]:
arr = np.array([1, 3, 5, 7])

x = np.searchsorted(arr, [2, 4, 6])

print(x)

[1 2 3]


<a name='6'></a>

# Filtrado
[regresar al contenido](#c1)

In [28]:
arr = np.array([41, 42, 43, 44])

filter_arr = arr > 42

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False False  True  True]
[43 44]


In [29]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

filter_arr = arr % 2 == 0

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False  True False  True False  True False]
[2 4 6]


EVIDENCIA DEL TRABAJO DE LA CLASE DEL 29 DE OCTUBRE DE 2024

In [30]:
a=[1,2,3,4]
b=[4,5,6,7]
a+b

import numpy as np
a=np.array([1,2,3,4])  #Esto ya es un arreglo

print(type(a))
print(a)

<class 'numpy.ndarray'>
[1 2 3 4]


DIMENSIÓN CERO:

Los arreglos de dimensión 0 son aquellos que no tienen corchetes

In [31]:
dim_cero=np.array(1)
#Arreglo de dimensión cero, corresponden a los escalares en geometría analítica
print(dim_cero)

1


DIMENSIÓN UNO

La diferencia con los de dimencón 0 es el número de corchetes que tengo, en el caso de tener un par de corchetes son de dimensión uno.

In [32]:
dim_uno=np.array([2,3])
#Arreglo de dimensión uno, es lo que corresponde en geometría analítica a los vectores
print(dim_uno)

[2 3]


DIMENSIÓN DOS

Son aquellos que tienen corchetes dentro de corchetes.

In [33]:
dim_dos=np.array([[1,2],[3,4]])
#Arreglo de dimensión dos, que son los que corresponden a las matrices en geometría analítica;
#por lo tanto se debe de respetar la estructura de una matriz tradicional, de lo contrario nos va  a marcar un error
print(dim_dos)

#El número de filas de la matriz va a correponder al número de elementos dentro e los corchetes grandes,
#mientras que el número de columnas va a acorresponder a los elementos dentro de cada paréntesis pequeño.

[[1 2]
 [3 4]]


Cuando se recibe un arreglo, para conocer su dimensión se puede usar el siguiente comando, donde nosotros simplemente ponemos el arreglo  en automático nos dice su dimensión.

In [34]:
print(dim_cero.ndim)
print(dim_uno.ndim)
print(dim_dos.ndim)

0
1
2


Para saber el número de elementos dentro de un arreglo, se puede usar el siguiente comando.

In [35]:
print(dim_cero.shape)
print(dim_uno.shape)
print(dim_dos.shape)

()
(2,)
(2, 2)


Dentro de las variables no se pueden poner datos que no sean del mismo tipo, se pueden pner booleanos y se traducen en unos y ceros, tambien se pueden meter variables  siempre y cuando se hayan declarado desde antes

In [4]:
import numpy as np
A=np.array([[ 1/2 , 1 , 3/4 ] , [ 2 , 4 ,5 ]])

B=np.array([[1/2 ,1 , 3/4],["o",1,True],[2,4,5]])
print(A)
print(B)

[[0.5  1.   0.75]
 [2.   4.   5.  ]]
[['0.5' '1' '0.75']
 ['o' '1' 'True']
 ['2' '4' '5']]


Se pueden hacer arreglos de diccionarios, de tuplas, pero no de arreglos con diferentes tipos de datos

In [7]:
import numpy as np

B=np.array([[1/2 ,1 , 3/4],[o,1,True],[2,4,5]])

print(B)

NameError: name 'o' is not defined

Para imprimir elguno de los elementos del arreglo

In [9]:
vec=np.array([2 , 0 , -1 , 4 , 5])
print(vec[0])
print(vec[3])
print(vec[-1])
print(vec[-2])

2
4
5
4


En el slicing el primer número corresponde al elemento en donde coienza, y el segundo indica quese detiene uno antes de ese número.

In [14]:
vec=np.array([2 , 0 , -1 , 4 , 5])
n=len(vec)
print(n)
print(vec[0:4])
print(vec[2:5])


5
[ 2  0 -1  4]
[-1  4  5]
[ 2  0 -1  4  5]


Hay una forma de hacer un pocomás dimámico el slicing, ya que se puede dar un rango del cual e quieren tomar números cada cierta cantidad. El primero es la posición desde la que comienzo, la segunda es hasta la que llego uno antes y la última hace referencia caa cuanto se toman los números/elementos.

In [16]:
vec=np.array([2,0,-1,4,5,6,7,8,9,10])
print(vec[1:10:2])


[ 0  4  6  8 10]


In [22]:
Mat=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

#Acceder al 2
print(Mat[0,1])

#Acceder al 11
print(Mat[2,2])

#Acceder al 8
print(Mat[1,-1])

#Acceder al 12
print(Mat[-1,-1])

print(Mat[1,4])
#Error de sintaxis

2
11
8
12


IndexError: index 4 is out of bounds for axis 1 with size 4

IMPRIMIR COLUMNAS

In [25]:
print(Mat[:,0])
print(Mat[:,1])
print(Mat[:,2])
print(Mat[:,3])

[1 5 9]
[ 2  6 10]
[ 3  7 11]
[ 4  8 12]


IMPRIMIR FILAS

In [26]:
print(Mat[0,:])
print(Mat[1,:])
print(Mat[2,:])

[1 2 3 4]
[5 6 7 8]
[ 9 10 11 12]


Se puede combinar el slicing de columnas o filas con el slicing normal, lo único es que donde antes se ponían los dos puntos, ahora se pone el slicing normal.

In [36]:
print(Mat[1,1:4])
print()
print(Mat[1:3,2])
print()
print(Mat[1:3,1:4])
print()
#El primero cntrola filas y el segundo controla columnas
print(Mat[0:2,0:3])

[6 7 8]

[ 7 11]

[[ 6  7  8]
 [10 11 12]]

[[1 2 3]
 [5 6 7]]


In [44]:
a=np.array([1,2,3,4])
b=np.array([4,5,6,7])
print(a+b)
print(a*b)

print()
print(Mat+Mat)




[ 5  7  9 11]
[ 4 10 18 28]

[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]


In [52]:
a=np.array([1,2,3,4])
b=np.array([4,5,6,7])
suma=[]
for i in range(0,len(a)):
  sum=(a[i]+b[i])

print(sum)

11
