<a href="https://colab.research.google.com/github/LuisR-crypto/THC_LRNP_TAREAS/blob/main/Array_31-10-2024.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

EVIDENCIA DE LA CLASE DEL 31 DE OCTUBR DE 2024

In [2]:
#bibliotecas
import numpy as np

LINSPACE

Lo que hace este comando es que entreparéntesis ponemos tres números, de los cuales, los dos primeros corresponden a un intervalo, y el segundo a las partes en las que quiero que la divida menos uno

In [8]:
arreglo=np.linspace(0,2,16)
arreglo


array([0.        , 0.13333333, 0.26666667, 0.4       , 0.53333333,
       0.66666667, 0.8       , 0.93333333, 1.06666667, 1.2       ,
       1.33333333, 1.46666667, 1.6       , 1.73333333, 1.86666667,
       2.        ])

RESHAPE

Lo que hace el comando es que arregla los elementos del arreglo en una matriz, donde el primer número dentro del paréntesis corresponde al número de filas, mientras que el segundo valor son las columnas.

In [11]:
arreglo.reshape((4,4))

array([[0.        , 0.13333333, 0.26666667, 0.4       ],
       [0.53333333, 0.66666667, 0.8       , 0.93333333],
       [1.06666667, 1.2       , 1.33333333, 1.46666667],
       [1.6       , 1.73333333, 1.86666667, 2.        ]])

Se pueden hacer vectores columna, que se pueden obtener poniendo (-1,1), y ponemos crear matricez tanto cuadradas como rectangulares.


In [12]:
arreglo.reshape(-1,1)

array([[0.        ],
       [0.13333333],
       [0.26666667],
       [0.4       ],
       [0.53333333],
       [0.66666667],
       [0.8       ],
       [0.93333333],
       [1.06666667],
       [1.2       ],
       [1.33333333],
       [1.46666667],
       [1.6       ],
       [1.73333333],
       [1.86666667],
       [2.        ]])

COMPARATIVOS

In [14]:
arr=np.array([2,5,1,8,9,10,15,4,6])
#Como phyton está vectorizado al hacer la comaración, se va a ir elemento por elemnto del arreglo
#A esto se le llama máscara booleana, que nos sirve no sólo para saber si hay elemenots mayores de algúnnúmero
#sino que tambien podemos extraerlos para poder trabajar con ellos
arr>5

array([False, False, False,  True,  True,  True,  True, False,  True])

In [15]:
arr[arr>5]

array([ 8,  9, 10, 15,  6])

In [16]:
MB=arr>5
arr[MB]

array([ 8,  9, 10, 15,  6])

In [17]:
arr[arr % 2 == 0]
#Esto es una máscara booleana

array([ 2,  8, 10,  4,  6])

In [18]:
arr[arr<5]

array([2, 1, 4])

In [19]:
arr[(arr<10) and (arr>5)]
#(arr<10) and (arr>5) le es ambigua a la comutadora

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [22]:
arr1=arr[(arr<10)]
arr1[arr1>5]


array([8, 9, 6])

La forma anterior reasigna los valores del arreglo original y los asigna a arr1, por lo que en nuestros arreglos tenemos el original mas el nuevo que acabamos de crear

In [27]:
arr1=np.copy(arr)
arr1=arr1[arr1<10]
arr1=arr1[arr1>5]
arr1

array([8, 9, 6])

El anterior lo que hace es que sobreescribe nuestro arrelo original y se pierden los demás elementos que no cumplen las condiciones pedidas.

WHERE

In [29]:
arr2=np.where(arr%2==0) #Devuelve el arreglo con los elementos que son pares
arr[arr2]

array([8, 6])

#SEARCHSORTED

In [33]:
arr=np.array([2,5,1,8,9,10,15,4,6])
arr

array([ 2,  5,  1,  8,  9, 10, 15,  4,  6])

Usando el comndo np.sorted podemos reacomodar todos los elementos del arrglo para asípoder trabajar con él de una forma más fácil.

In [34]:
arr=np.sort(arr)
arr

array([ 1,  2,  4,  5,  6,  8,  9, 10, 15])

Mediante el comando searchsorted, podemos buscar el valor específico de uno de los elementos del arreglo, y nos va a regresar la posición en la que se encuentra ese elemento

In [36]:
index=np.searchsorted(arr,6)
index

5

In [38]:
np.mean(arr)

6.666666666666667

In [39]:
np.median(arr)

6.0

In [40]:
np.sum(arr)

60

#OPERACIONES DE ARREGLOS

In [41]:
arr+arr

array([ 2,  4,  8, 10, 12, 16, 18, 20, 30])

In [42]:
arr**2

array([  1,   4,  16,  25,  36,  64,  81, 100, 225])

In [43]:
np.dot(arr,arr)

552

In [44]:
arr*arr

array([  1,   4,  16,  25,  36,  64,  81, 100, 225])

In [45]:
arr/arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [46]:
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0])

#PROBLEMA DE CALENTAMIENTO

De un arreglo seleccione aquellos impares

In [49]:
vector=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13])

vector[vector%2==1]


array([ 1,  3,  5,  7,  9, 11, 13])

In [54]:
vector=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13])
vector1=np.where(vector % 2==1)
vector[vector1]



array([ 1,  3,  5,  7,  9, 11, 13])

Dados a, b en R2

Programe a*b (producto escalar)

In [55]:
a=[1,2,3]
b=[4,5,6]

ProdEsc=0.0
for i in range(len(a)):
   ProdEsc+=a[i]*b[i]
print(ProdEsc)

32.0


In [57]:
a=np.ones(20) #Lo que hace es que hace un arreglo de 20 números 1
b=np.ones(20)

ProdEsc=0.0
n=len(a)

for i in range(n):
  ProdEsc+=a[i]*b[i]

print(ProdEsc)

20.0


UNA FUNCIÓN QUE DADOS DOS VECTORES VALIDE QUE SEAN DE LA MISMA LONGITUD, EN CASO DE NO SERLO IMPRIME UN AVISO, EN CASO DE SERLO REALIZA EL PRODUCTO ESCALAR


In [62]:
a=input("Ingrese el priver vecto")
b=input("Ingrese el segundo vector")
a1=np.array(a)
b1=np.array(b)
def ProdEsc(a1,b1):
  if len(a)!=len(b):
   print("Los vectores introducidos no son de la misma longiitud, por lo que no se puede realizar el producto escalar")
  else:
    ProdEsc=0.0
    for i in range(len(a)):
      ProdEsc+=a1[i]+b1[i]
      print(ProdEsc)
print(ProdEsc(a1,b1))

Ingrese el priver vecto1,2,3
Ingrese el segundo vector4,5,6


TypeError: unsupported operand type(s) for +=: 'float' and 'str'

In [65]:
a=np.ones(20)
b=np.ones(20)
def ProductoEscalar(a,b):
  if len(a)==len(b):
    ProdEsc=0.0
    n=len(a)

    for i in range(n):
      ProdEsc+=a[i]*b[i]

    print(ProdEsc)
    return ProdEsc
  else:
    print("No se puede hacer la operación")
    return

resultado= ProductoEscalar(a,b)

20.0


In [70]:
A=np.array([[1.,1.,1.],[1.,1.,1.],[1.,1.,1.]])
b=np.array([1.,2.,3.])

def MatVec(A,b):
  x=np.zeros(len(b))
  for i in range(len(b)):
    x[i]=ProductoEscalar(A[i,:],b)

  return x
print(MatVec(A,b))


6.0
6.0
6.0
[6. 6. 6.]
